services:
    - docker

before_install:
    - docker build -t gabrielade/docker-react -f dev.Dockerfile .    

script:
    - docker run -e CI=true gabrielade/docker-react npm run test

deploy:
    edge: true # forcing Travis to use the v2 (experimental) version of the dpl script which does not have the bug.
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-986991386050"
    bucket_path: "Docker"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
    on:
        branch: master