sudo: required
services:
    - docker

before_install:
    - docker build -t gabrielade/docker-react -f dev.Dockerfile .    

script:
    - docker run gabrielade/docker-react npm run test -- --coverage    